// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Models;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20230521014020_AddedExpansionsandAlliances")]
    partial class AddedExpansionsandAlliances
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Server.Models.Alliance", b =>
                {
                    b.Property<string>("AllianceId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("AllianceId");

                    b.ToTable("Alliance");
                });

            modelBuilder.Entity("Server.Models.Expansion", b =>
                {
                    b.Property<string>("ExpansionId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ExpansionId");

                    b.ToTable("Expansion");
                });

            modelBuilder.Entity("Server.Models.Location", b =>
                {
                    b.Property<string>("LocationId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AllianceId")
                        .HasColumnType("int");

                    b.Property<string>("AllianceId1")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExpansionId")
                        .HasColumnType("int");

                    b.Property<string>("ExpansionId1")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Latitude")
                        .HasColumnType("int");

                    b.Property<int>("Longitude")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("LocationId");

                    b.HasIndex("AllianceId1");

                    b.HasIndex("ExpansionId1");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Server.Models.Location", b =>
                {
                    b.HasOne("Server.Models.Alliance", "Alliance")
                        .WithMany("Locations")
                        .HasForeignKey("AllianceId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Expansion", "Expansion")
                        .WithMany("Locations")
                        .HasForeignKey("ExpansionId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alliance");

                    b.Navigation("Expansion");
                });

            modelBuilder.Entity("Server.Models.Alliance", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("Server.Models.Expansion", b =>
                {
                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
